services:
  mongodb:
    image: mongo:8
    container_name: jobtracker-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  
  api:
    build:
      context: ./apps/api
    container_name: jobtracker-api
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - ./apps/api/.env
    ports:
      - "4000:4000"

volumes:
  mongodb_data: