apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  NODE_ENV: "development"
  PORT: "4000"
  CLIENT_ORIGIN: "http://localhost:5173, http://127.0.0.1:5173"
  MONGODB_URI: "mongodb://mongodb:27017/jobtracker"